🍱asset:
- changed-files:
  - any-glob-to-any-file: ['app/favicon.ico', 'public/**', 'app/**/*.png', 'app/**/*.svg']
♻️ci:
- changed-files:
  - any-glob-to-any-file: '.github/**/*.yml'
⚙️config:
- changed-files:
  - any-glob-to-any-file: '*config.*'
📦dependencies:
- changed-files:
  - any-glob-to-any-file: ['bun.lockb', 'package.json']
docker:
- changed-files:
  - any-glob-to-any-file: ['.dockerignore', 'Dockerfile']
📝documentation:
- changed-files:
  - any-glob-to-any-file: ['**/*.md', '**/*.txt']
🚀enhancement:
- head-branch: ['^feature', 'feature', '^enhancement', 'enhancement']
✨feature:
- all:
  - changed-files:
    - any-glob-to-any-file: 'app/**'
    - all-globs-to-all-files: '!app/**/*.test.tsx'
🪸git:
- changed-files:
  - any-glob-to-any-file: ['.gitattributes', '.gitignore']
🧰infrastructure:
- changed-files:
  - any-glob-to-any-file: ['.devcontainer/*', '.editorconfig', '.env*', 'biome.json', 'bunfig.toml']
✅test:
- changed-files:
  - any-glob-to-any-file: ['happydom.ts', 'app/**/*.test.tsx']
🆚vscode:
- changed-files:
  - any-glob-to-any-file: '.vscode/*'
